### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by waky80** [snuspl/nimble#7]
I tried building Nimble.
I had the following error.
Can you help me?

Than you.

=========================================================================================
 
[1581/2921] Building NVCC (Device) object caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_UnaryOpsKernel.cu.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "setup.py", line 755, in <module>
    build_deps()
  File "setup.py", line 316, in build_deps
    cmake=cmake)
  File "/root/nimble/tools/build_pytorch_libs.py", line 62, in build_caffe2
    cmake.build(my_env)
  File "/root/nimble/tools/setup_helpers/cmake.py", line 335, in build
    self.run(build_args, my_env)
  File "/root/nimble/tools/setup_helpers/cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/root/anaconda3/envs/nimble/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '48']' returned non-zero exit status 1.

**Comment by gyeongin** [comment]
Thanks for you interest!
I think this error is not relevant to the changes (for Nimble) we've made in PyTorch's codebase.
In fact, the log that you've attached above has no information about which part of the code made the compilation unsuccessful.
Can you first "clean" your build history (simply run `python setup.py clean`) and then retry the build again?

If you still have problem after cleaning the history, I think you should first try building **PyTorch v1.4.1** because I expect you will have the same problem in building the original PyTorch codebase.
